print("Christine Anne S. Lopez")
print("Pinggan, Gasan, Marinduque")
print("April 19, 2002")
print("Marinduque State College")
print("BS Information Technology")
print("2nd year, Section: D")
print("cooking")
print("sleeping")
print("watching movies")
print("playing online games")
print("reading fictional books")